//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SGR
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Mesa> Mesa
        {
            get
            {
                if ((_Mesa == null))
                {
                    _Mesa = base.CreateObjectSet<Mesa>("Mesa");
                }
                return _Mesa;
            }
        }
        private ObjectSet<Mesa> _Mesa;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mesa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMesa(Mesa mesa)
        {
            base.AddObject("Mesa", mesa);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="Mesa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mesa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Mesa object.
        /// </summary>
        /// <param name="iD_Mesa">Initial value of the ID_Mesa property.</param>
        public static Mesa CreateMesa(global::System.Int32 iD_Mesa)
        {
            Mesa mesa = new Mesa();
            mesa.ID_Mesa = iD_Mesa;
            return mesa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Mesa
        {
            get
            {
                return _ID_Mesa;
            }
            set
            {
                if (_ID_Mesa != value)
                {
                    OnID_MesaChanging(value);
                    ReportPropertyChanging("ID_Mesa");
                    _ID_Mesa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Mesa");
                    OnID_MesaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Mesa;
        partial void OnID_MesaChanging(global::System.Int32 value);
        partial void OnID_MesaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mesa1
        {
            get
            {
                return _mesa1;
            }
            set
            {
                Onmesa1Changing(value);
                ReportPropertyChanging("mesa1");
                _mesa1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mesa1");
                Onmesa1Changed();
            }
        }
        private Nullable<global::System.Int32> _mesa1;
        partial void Onmesa1Changing(Nullable<global::System.Int32> value);
        partial void Onmesa1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nlugares
        {
            get
            {
                return _nlugares;
            }
            set
            {
                OnnlugaresChanging(value);
                ReportPropertyChanging("nlugares");
                _nlugares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nlugares");
                OnnlugaresChanged();
            }
        }
        private Nullable<global::System.Int32> _nlugares;
        partial void OnnlugaresChanging(Nullable<global::System.Int32> value);
        partial void OnnlugaresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> esplanada
        {
            get
            {
                return _esplanada;
            }
            set
            {
                OnesplanadaChanging(value);
                ReportPropertyChanging("esplanada");
                _esplanada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("esplanada");
                OnesplanadaChanged();
            }
        }
        private Nullable<global::System.Boolean> _esplanada;
        partial void OnesplanadaChanging(Nullable<global::System.Boolean> value);
        partial void OnesplanadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Emp_Cod
        {
            get
            {
                return _Emp_Cod;
            }
            set
            {
                OnEmp_CodChanging(value);
                ReportPropertyChanging("Emp_Cod");
                _Emp_Cod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Emp_Cod");
                OnEmp_CodChanged();
            }
        }
        private Nullable<global::System.Int32> _Emp_Cod;
        partial void OnEmp_CodChanging(Nullable<global::System.Int32> value);
        partial void OnEmp_CodChanged();

        #endregion

    
    }

    #endregion

    
}
